### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by AlucardSama04** [akai-katto/dandere2x#147]
I'm trying to upscale an episode from Shaman King using Dandere2x but when I press "Upscale!" button, I get this:

Traceback (most recent call last):
  File "gui_driver.py", line 214, in press_upscale_button
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\George\\Desktop\\Dandere2X\\'

**Comment by AverytheFurry** [comment]
![image](https://user-images.githubusercontent.com/47131867/94098166-e41d9d80-fddc-11ea-9ddb-fbf0bdaea1a8.png)
Same issue

**Comment by aka-katto** [comment]
Which version? 

Also, did you hit "download externals" button first?

**Comment by AlucardSama04** [comment]
Last version and yes.

**Comment by aka-katto** [comment]
Sorry for the slow response, 


I believe the issue is that you need to install this into a pre-existing dandere2x directory 

I forgot to label the latest version as a pre-release

https://github.com/aka-katto/dandere2x/releases/tag/2.1

Install the binary you have to this installation, and let me know if it works

**Comment by LastBreeze** [comment]
Having this same issue with 2.01r, and with the latest version copied into the 201.r folder

**Comment by FlashlightET** [comment]
same here

**Comment by peepopoggers** [comment]
For most people, download externals will work.
