### ISSUE TITLE
Video Settings from Yaml dont get read or get ignored.

### ISSUE THREAD

**Issue by kvanbiesen** [akai-katto/dandere2x#190]
EAsiest to detect. Defaul yaml file says CRF 17

Mediainfo output says CRF 23. Latest 3.03 version.

also noticable in output window....missing the parameters from the yaml for ffmpeg :)

https://imgur.com/a/QgNCXSV

**Comment by akai-katto** [comment]
So some explanation,

Dandere2x has three ffmpeg actions:

- re-encode video
- pipe images to video
- migrate audio from piped video into a finished video.

The reason that the optional / missing parameters aren't showing up in the debug statement is since that falls under "pipe_frames_to_video", but good catch on the CRF issue, I forgot to add the `-c copy` flag to copy the video with new audio, not re-encode it. 

The 3.1.1 patch should fix this, which I will bundle as a complete release tonight. You can find the patch in the current 3.0 downloads though.

**Comment by akai-katto** [comment]
https://github.com/akai-katto/dandere2x/releases/tag/3%2C1

Re-open if you still have issues

**Comment by kvanbiesen** [comment]
Yup seems, to fix it.

Yeah i was sure it was ignored somerwhere but didnt knew where. 
New to the app and still experimenting :D

Tried encoding with an exotic video/audio codec and it picked up both so this can stay closed :)
